"""Static seed content: 42 topics + sample trilingual questions."""

# (name_uz, name_ru) — name_kaa defaults to name_uz (admin can refine later)
TOPICS = [
    ("Umumiy qoidalar", "Общие положения"),
    ("Haydovchilarning umumiy majburiyatlari", "Общие обязанности водителей"),
    ("Ogohlantiruvchi belgilar", "Предупреждающие знаки"),
    ("Ustunlik belgilari", "Знаки приоритета"),
    ("Taqiqlovchi belgilar", "Запрещающие знаки"),
    ("Buyuruvchi belgilar", "Предписывающие знаки"),
    ("Axborot-ishora belgilari", "Информационно-указательные знаки"),
    ("Servis belgilari", "Знаки сервиса"),
    ("Qo'shimcha axborot belgilari", "Знаки дополнительной информации"),
    ("Yo'l chiziqlari (razmetka)", "Дорожная разметка"),
    ("Svetofor ishoralari", "Сигналы светофора"),
    ("Nizomchi ishoralari", "Сигналы регулировщика"),
    ("Ogohlantiruvchi signallar", "Предупредительные сигналы"),
    ("Harakatni boshlash va manevr qilish", "Начало движения, маневрирование"),
    ("Yo'lda joylashish", "Расположение ТС на проезжей части"),
    ("Harakat tezligi", "Скорость движения"),
    ("Quvib o'tish va qarama-qarshi o'tish", "Обгон, встречный разъезд"),
    ("To'xtash va to'xtab turish", "Остановка и стоянка"),
    ("Chorrahalardan o'tish", "Проезд перекрёстков"),
    ("Piyodalar o'tish joylari", "Пешеходные переходы"),
    ("Temir yo'l kesishmalari", "Железнодорожные переезды"),
    ("Avtomagistralda harakatlanish", "Движение по автомагистралям"),
    ("Turar joy zonalarida harakat", "Движение в жилых зонах"),
    ("Yo'lovchilarni tashish", "Перевозка пассажиров"),
    ("Yuklarni tashish", "Перевозка грузов"),
    ("Velosiped va mopedlar harakati", "Движение велосипедов и мопедов"),
    ("Tashqi yoritish asboblari", "Внешние световые приборы"),
    ("Shoshilinch xizmat transporti", "Транспорт экстренных служб"),
    ("Mexanik vositalarni shatakka olish", "Буксировка механических ТС"),
    ("O'quv haydash", "Учебная езда"),
    ("Texnik nosozliklar", "Неисправности и условия эксплуатации"),
    ("Transport vositalari turkumlari", "Категории транспортных средств"),
    ("Haydovchilik guvohnomasi", "Водительское удостоверение"),
    ("Yo'l harakati xavfsizligi asoslari", "Основы безопасности движения"),
    ("Yo'l-transport hodisalari", "Дорожно-транспортные происшествия"),
    ("Birinchi tibbiy yordam", "Первая медицинская помощь"),
    ("Avtomobil tuzilishi asoslari", "Основы устройства автомобиля"),
    ("Ekologik xavfsizlik", "Экологическая безопасность"),
    ("Haydovchi javobgarligi", "Ответственность водителя"),
    ("Sug'urta (OSAGO)", "Страхование (ОСАГО)"),
    ("Ekstremal sharoitlarda haydash", "Вождение в экстремальных условиях"),
    ("Yo'l harakati psixologiyasi", "Психология дорожного движения"),
]


def _q(topic_id, uz, kaa, ru, options, e_uz="", e_kaa="", e_ru=""):
    return {
        "topic_id": topic_id,
        "text": {"uz": uz, "kaa": kaa, "ru": ru},
        "explanation": {"uz": e_uz, "kaa": e_kaa, "ru": e_ru},
        "options": [
            {"text": {"uz": o[0], "kaa": o[1], "ru": o[2]}, "is_correct": o[3]}
            for o in options
        ],
    }


# 24 sample questions, each in 3 languages (uz / kaa / ru)
QUESTIONS = [
    _q(
        1,
        "«Yo'l harakati» atamasi nimani anglatadi?",
        "«Jol háreketi» termini nени ańlatadı?",
        "Что означает термин «Дорожное движение»?",
        [
            ("Yo'llarda transport va piyodalar harakati jarayoni",
             "Jollarda transport hám jayaw júriwshilerdiń háreketi",
             "Процесс перемещения транспорта и пешеходов по дорогам", True),
            ("Faqat yengil avtomobillar harakati",
             "Tek jeńil avtomobiller háreketi",
             "Только движение легковых автомобилей", False),
            ("Faqat shahar ichidagi harakat",
             "Tek qala ishindegi háreket",
             "Только движение внутри города", False),
        ],
        "Yo'l harakati — bu yo'llarda odamlar va yuklarning transport vositalari yordamida yoki ularsiz ko'chish jarayoni.",
        "",
        "Дорожное движение — процесс перемещения людей и грузов по дорогам.",
    ),
    _q(
        3,
        "Ushbu belgi qaysi guruhga mansub: u xavf haqida ogohlantiradimi?",
        "Bul belgi qaysı toparǵa tiyisli: ol qáwip haqqında eskertedi me?",
        "Предупреждающие знаки служат для чего?",
        [
            ("Haydovchini yaqinlashayotgan xavf haqida ogohlantirish uchun",
             "Haydawshını jaqınlasıp atırǵan qáwip haqqında eskertiw ushın",
             "Чтобы предупредить водителя о приближении к опасному участку", True),
            ("Harakatni butunlay taqiqlash uchun",
             "Háreketti pútkilley qadaǵan etiw ushın",
             "Чтобы полностью запретить движение", False),
            ("Yo'nalishni ko'rsatish uchun",
             "Baǵdardı kórsetiw ushın",
             "Чтобы указать направление", False),
        ],
    ),
    _q(
        5,
        "Taqiqlovchi belgilar nima vazifani bajaradi?",
        "Qadaǵan etiwshi belgiler qanday wazıypa atqaradı?",
        "Какую функцию выполняют запрещающие знаки?",
        [
            ("Ma'lum harakatlarni cheklaydi yoki taqiqlaydi",
             "Belgili háreketlerdi sheklaydı yamasa qadaǵan etedi",
             "Ограничивают или запрещают определённые действия", True),
            ("Servis joylarini ko'rsatadi",
             "Servis orınların kórsetedi",
             "Указывают места сервиса", False),
            ("Yo'l nomini bildiradi",
             "Jol atın bildiredi",
             "Сообщают название дороги", False),
        ],
    ),
    _q(
        11,
        "Svetoforning qizil chirog'i nimani bildiradi?",
        "Svetofordıń qızıl shıraǵı nени bildiredi?",
        "Что означает красный сигнал светофора?",
        [
            ("Harakatlanish taqiqlanadi",
             "Háreketleniw qadaǵan etiledi",
             "Движение запрещено", True),
            ("Harakatlanishga ruxsat",
             "Háreketleniwge ruqsat",
             "Движение разрешено", False),
            ("Tezlikni oshirish kerak",
             "Tezlikti asırıw kerek",
             "Нужно увеличить скорость", False),
        ],
        "Qizil chiroq yonganda transport vositasi to'xtash chizig'i oldida to'xtashi shart.",
        "",
        "При красном сигнале ТС обязано остановиться перед стоп-линией.",
    ),
    _q(
        11,
        "Svetoforning sariq chirog'i (qizildan keyin) yonsa, nima qilinadi?",
        "Svetofordıń sarı shıraǵı (qızıldan keyin) jansa, ne isleydi?",
        "Что делать при жёлтом сигнале (после красного)?",
        [
            ("Harakatga tayyorlanib turish, lekin hali boshlamaslik",
             "Háreketke tayarlanıp turıw, biraq ele baslamaw",
             "Подготовиться к движению, но пока не начинать", True),
            ("Darhol harakatni boshlash",
             "Derhal háreketti baslaw",
             "Немедленно начать движение", False),
            ("Orqaga yurish",
             "Artqa júriw",
             "Двигаться назад", False),
        ],
    ),
    _q(
        16,
        "Aholi punktlarida umumiy holatda ruxsat etilgan eng katta tezlik qancha?",
        "Xalıq punktlerinde ulıwma jaǵdayda ruqsat etilgen eń joqarı tezlik qansha?",
        "Какова максимальная скорость в населённых пунктах?",
        [
            ("70 km/soat", "70 km/saat", "70 км/ч", True),
            ("90 km/soat", "90 km/saat", "90 км/ч", False),
            ("60 km/soat", "60 km/saat", "60 км/ч", False),
            ("110 km/soat", "110 km/saat", "110 км/ч", False),
        ],
        "O'zbekistonda aholi punktlarida umumiy tezlik chegarasi 70 km/soat.",
        "",
        "В населённых пунктах общее ограничение скорости — 70 км/ч.",
    ),
    _q(
        18,
        "«To'xtash» va «To'xtab turish» o'rtasidagi farq nimada?",
        "«Toqtaw» hám «Toqtap turıw» arasındaǵı parq nede?",
        "В чём разница между «остановкой» и «стоянкой»?",
        [
            ("To'xtab turish 5 daqiqadan ortiq vaqtni nazarda tutadi",
             "Toqtap turıw 5 minuttan artıq waqıttı názerde tutadı",
             "Стоянка — это прекращение движения более чем на 5 минут", True),
            ("Hech qanday farqi yo'q",
             "Hesh qanday parqı joq",
             "Никакой разницы нет", False),
            ("To'xtash faqat tunda bo'ladi",
             "Toqtaw tek túnde boladı",
             "Остановка бывает только ночью", False),
        ],
    ),
    _q(
        19,
        "Teng ahamiyatli chorrahada kim ustunlikka ega?",
        "Teń áhmiyetli kóshe qiyılısında kim ústinlikke iye?",
        "Кто имеет приоритет на перекрёстке равнозначных дорог?",
        [
            ("O'ngdan kelayotgan transport vositasi",
             "Oń tárepten kiyatırǵan transport vositası",
             "Транспорт, приближающийся справа", True),
            ("Chapdan kelayotgan transport",
             "Shep tárepten kiyatırǵan transport",
             "Транспорт, приближающийся слева", False),
            ("Kattaroq transport vositasi",
             "Úlkenirek transport vositası",
             "Более крупное транспортное средство", False),
        ],
        "Teng ahamiyatli chorrahada «o'ng qo'l qoidasi» amal qiladi.",
        "",
        "На равнозначном перекрёстке действует правило «помехи справа».",
    ),
    _q(
        20,
        "Piyodalar o'tish joyida haydovchi nima qilishi kerak?",
        "Jayaw ótiw oríninda haydawshı ne islewi kerek?",
        "Как должен поступить водитель на пешеходном переходе?",
        [
            ("O'tayotgan piyodalarga yo'l berishi shart",
             "Ótip atırǵan jayaw júriwshilerge jol beriwi shárt",
             "Уступить дорогу пешеходам", True),
            ("Signal berib o'tib ketishi mumkin",
             "Signal berip ótip ketiwi múmkin",
             "Можно проехать, подав сигнал", False),
            ("Tezlikni oshirishi kerak",
             "Tezlikti asırıwı kerek",
             "Увеличить скорость", False),
        ],
    ),
    _q(
        2,
        "Haydovchi yo'lga chiqishdan oldin nimaga ishonch hosil qilishi kerak?",
        "Haydawshı jolǵa shıǵıwdan aldın neге isenim payda etiwi kerek?",
        "В чём водитель должен убедиться перед выездом?",
        [
            ("Transport vositasining texnik holati soz ekanligiga",
             "Transport vositasınıń texnikalıq jaǵdayı durıs ekenine",
             "В исправности транспортного средства", True),
            ("Yoqilg'i narxiga",
             "Janılǵı bahasına",
             "В цене на топливо", False),
            ("Ob-havo prognozining aniqligiga",
             "Hawa rayı prognozınıń anıqlıǵına",
             "В точности прогноза погоды", False),
        ],
    ),
    _q(
        36,
        "Qon ketishini to'xtatishning eng tez usuli qaysi?",
        "Qan ketiwin toqtatıwdıń eń tez usılı qaysı?",
        "Какой способ остановки кровотечения самый быстрый?",
        [
            ("Jarohat ustidan barmoq bilan bosish",
             "Jaraqat ústinen barmaq penen basıw",
             "Прижатие раны пальцем", True),
            ("Jarohatni suv bilan yuvish",
             "Jaraqattı suw menen juwıw",
             "Промывание раны водой", False),
            ("Hech narsa qilmaslik",
             "Hesh nárse islemew",
             "Ничего не делать", False),
        ],
        "Arterial qon ketishda zudlik bilan tomirni bosish hayot saqlaydi.",
        "",
        "При артериальном кровотечении немедленное прижатие сосуда спасает жизнь.",
    ),
    _q(
        27,
        "Tunda yo'l yoritilmagan bo'lsa, qaysi faralardan foydalaniladi?",
        "Túnde jol jaqtılandırılmaǵan bolsa, qaysı faralar paydalanıladı?",
        "Какие фары используются ночью на неосвещённой дороге?",
        [
            ("Uzoq yoki yaqin nur faralari",
             "Uzaq yamasa jaqın nur faraları",
             "Дальний или ближний свет фар", True),
            ("Faqat gabarit chiroqlari",
             "Tek gabarit shıraqları",
             "Только габаритные огни", False),
            ("Hech qanday chiroq",
             "Hesh qanday shıraq",
             "Никакие огни", False),
        ],
    ),
    _q(
        17,
        "Quvib o'tish qaysi tomondan amalga oshiriladi?",
        "Quwıp ótiw qaysı tárepten ámelge asırıladı?",
        "С какой стороны выполняется обгон?",
        [
            ("Chap tomondan", "Shep tárepten", "С левой стороны", True),
            ("O'ng tomondan", "Oń tárepten", "С правой стороны", False),
            ("Istalgan tomondan", "Qálegen tárepten", "С любой стороны", False),
        ],
    ),
    _q(
        21,
        "Temir yo'l kesishmasiga yaqinlashganda haydovchi nima qiladi?",
        "Temir jol qiyılısına jaqınlasqanda haydawshı ne isleydi?",
        "Как действовать при приближении к ж/д переезду?",
        [
            ("Tezlikni kamaytirib, poyezd yo'qligiga ishonch hosil qiladi",
             "Tezlikti kemeytirip, poyezd joqlıǵına isenim payda etedi",
             "Снизить скорость и убедиться в отсутствии поезда", True),
            ("Tezlikni oshirib o'tib ketadi",
             "Tezlikti asırıp ótip ketedi",
             "Проехать на повышенной скорости", False),
            ("Relslar ustida to'xtaydi",
             "Rels ústinde toqtaydı",
             "Остановиться на рельсах", False),
        ],
    ),
    _q(
        14,
        "Manevr (o'ng/chapga burilish) oldidan haydovchi nima qiladi?",
        "Manevr (oń/shepke buralıw) aldınan haydawshı ne isleydi?",
        "Что делает водитель перед манёвром (поворотом)?",
        [
            ("Burilish ko'rsatkichini yoqadi",
             "Buralıw kórsetkishin jaǵadı",
             "Включает указатель поворота", True),
            ("Signal beradi",
             "Signal beredi",
             "Подаёт звуковой сигнал", False),
            ("Hech narsa qilmaydi",
             "Hesh nárse islemeydi",
             "Ничего не делает", False),
        ],
    ),
    _q(
        4,
        "Ustunlik belgilari nima uchun kerak?",
        "Ústinlik belgileri ne ushın kerek?",
        "Для чего нужны знаки приоритета?",
        [
            ("O'tish navbatini belgilash uchun",
             "Ótiw gezegin belgilew ushın",
             "Чтобы установить очерёдность проезда", True),
            ("Tezlikni cheklash uchun",
             "Tezlikti sheklew ushın",
             "Чтобы ограничить скорость", False),
            ("To'xtashni taqiqlash uchun",
             "Toqtawdı qadaǵan etiw ushın",
             "Чтобы запретить остановку", False),
        ],
    ),
    _q(
        10,
        "Uzluksiz uzun chiziq (razmetka) nimani bildiradi?",
        "Úzliksiz uzın sızıq (razmetka) nени bildiredi?",
        "Что означает сплошная линия разметки?",
        [
            ("Uni kesib o'tish taqiqlanadi",
             "Onı kesip ótiw qadaǵan etiledi",
             "Её пересечение запрещено", True),
            ("Uni istalgan vaqtda kesish mumkin",
             "Onı qálegen waqıtta kesiw múmkin",
             "Её можно пересекать в любое время", False),
            ("U faqat bezak",
             "Ol tek bezek",
             "Это просто украшение", False),
        ],
    ),
    _q(
        24,
        "Bolalarni avtomobilda tashishda nima talab qilinadi?",
        "Balalardı avtomobilde tasıwda ne talap etiledi?",
        "Что требуется при перевозке детей в автомобиле?",
        [
            ("Maxsus bolalar o'rindig'i",
             "Arnawlı balalar orındıǵı",
             "Специальное детское кресло", True),
            ("Hech narsa shart emas",
             "Hesh nárse shárt emes",
             "Ничего не требуется", False),
            ("Faqat old o'rindiqda o'tirishi",
             "Tek aldıńǵı orındıqta otırıwı",
             "Сидеть только на переднем сиденье", False),
        ],
    ),
    _q(
        31,
        "Tormoz tizimi nosoz bo'lsa, haydovchi nima qiladi?",
        "Tormoz sisteması nasaz bolsa, haydawshı ne isleydi?",
        "Что делать при неисправности тормозной системы?",
        [
            ("Harakatni davom ettirish taqiqlanadi",
             "Háreketti dawam etiw qadaǵan etiledi",
             "Движение запрещено", True),
            ("Sekin yurib davom etish mumkin",
             "Áste júrip dawam etiw múmkin",
             "Можно ехать медленно", False),
            ("Faqat tunda yurish mumkin",
             "Tek túnde júriw múmkin",
             "Можно ехать только ночью", False),
        ],
    ),
    _q(
        22,
        "Avtomagistralda nima taqiqlanadi?",
        "Avtomagistralda ne qadaǵan etiledi?",
        "Что запрещено на автомагистрали?",
        [
            ("Piyodalar harakati va ortga qaytish",
             "Jayaw júriw hám artqa qaytıw",
             "Движение пешеходов и разворот", True),
            ("70 km/soat tezlik",
             "70 km/saat tezlik",
             "Скорость 70 км/ч", False),
            ("Yengil avtomobillar harakati",
             "Jeńil avtomobiller háreketi",
             "Движение легковых автомобилей", False),
        ],
    ),
    _q(
        26,
        "Velosipedchi necha yoshdan yo'lda harakatlanishi mumkin?",
        "Velosipedshi neshe jastan jolda háreketleniwi múmkin?",
        "С какого возраста велосипедист может двигаться по дороге?",
        [
            ("14 yoshdan", "14 jastan", "С 14 лет", True),
            ("10 yoshdan", "10 jastan", "С 10 лет", False),
            ("18 yoshdan", "18 jastan", "С 18 лет", False),
        ],
    ),
    _q(
        13,
        "Tovush signalidan shahar ichida qachon foydalanish mumkin?",
        "Dawıs signalınan qala ishinde qashan paydalanıw múmkin?",
        "Когда в городе можно использовать звуковой сигнал?",
        [
            ("Faqat baxtsiz hodisaning oldini olish uchun",
             "Tek baxıtsız waqıyanıń aldın alıw ushın",
             "Только для предотвращения ДТП", True),
            ("Istalgan vaqtda",
             "Qálegen waqıtta",
             "В любое время", False),
            ("Salom berish uchun",
             "Sálem beriw ushın",
             "Чтобы поприветствовать", False),
        ],
    ),
    _q(
        35,
        "Yo'l-transport hodisasi yuz bersa, haydovchi birinchi navbatda nima qiladi?",
        "Jol-transport waqıyası júz berse, haydawshı birinshi gezekte ne isleydi?",
        "Что водитель делает в первую очередь при ДТП?",
        [
            ("Transportni to'xtatib, ogohlantirish belgisini o'rnatadi",
             "Transporttı toqtatıp, eskertiw belgisin ornatadı",
             "Останавливает ТС и выставляет знак аварийной остановки", True),
            ("Joydan tezda ketadi",
             "Orınnan tez ketedi",
             "Быстро уезжает с места", False),
            ("Hech kimga aytmaydi",
             "Hesh kimge aytpaydı",
             "Никому не сообщает", False),
        ],
    ),
    _q(
        6,
        "Buyuruvchi belgilar nimani ko'rsatadi?",
        "Buyrıwshı belgiler nени kórsetedi?",
        "Что указывают предписывающие знаки?",
        [
            ("Majburiy harakat yo'nalishini",
             "Májburiy háreket baǵdarın",
             "Обязательное направление движения", True),
            ("Taqiqlangan harakatlarni",
             "Qadaǵan etilgen háreketlerdi",
             "Запрещённые действия", False),
            ("Servis ob'ektlarini",
             "Servis obъektlerin",
             "Объекты сервиса", False),
        ],
    ),
]
